version: '3.8'

services:
  # Main application service - gunakan build lokal dulu
  notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-app
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - notes-network
    environment:
      - NODE_ENV=production
    labels:
      - "com.example.description=Notes App Web Server"
      - "com.example.version=1.0.0"
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower untuk auto-update
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_DEBUG=true
    networks:
      - notes-network
    profiles:
      - auto-update

networks:
  notes-network:
    driver: bridge
    name: notes-network