services:
  notes-app:
    image: ghcr.io/thorfinshine/restful-api-notes-app:latest
    container_name: notes-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - notes-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro  # Mount docker config for auth
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_DEBUG=true
      - DOCKER_CONFIG=/config.json
    command: --interval 300 --cleanup --label-enable
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
    name: notes-network