name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Check code formatting
      - name: Check code formatting
        run: |
          if npm run | grep -q "format:check"; then
            npm run format:check
          else
            echo "No format:check script found, skipping..."
          fi
        continue-on-error: true
      
      # Run tests
      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No test script found, skipping..."
          fi
        continue-on-error: true
      
      # Build check
      - name: Build check
        run: npm run build
      
      # Upload PR build artifacts - UPDATED TO V4
      - name: Upload PR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-${{ github.event.pull_request.number }}
          path: dist/
          retention-days: 3
      
      # Comment on PR with build status
      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const message = `
            ## 🤖 Build Status Report
            
            - ✅ Dependencies installed successfully
            - ✅ Build completed successfully
            - ℹ️ Tests and linting checks may need attention
            
            **Bundle Size**: Check artifacts for detailed report
            **Artifact**: pr-build-${{ github.event.pull_request.number }}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });