name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Check code formatting
      - name: Check code formatting
        run: npm run format:check
        continue-on-error: true
      
      # Run tests
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      # Build check
      - name: Build check
        run: npm run build
      
      # Comment on PR with build status
      - name: Comment PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const message = `
            ## 🤖 Build Status Report
            
            - ✅ Dependencies installed successfully
            - ✅ Build completed successfully
            - ℹ️ Tests and linting checks may need attention
            
            **Bundle Size**: Check artifacts for detailed report
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });