name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      # Create zip file of dist folder
      - name: Create release archive
        run: |
          if [ -d "dist" ]; then
            zip -r notes-app-${{ github.ref_name }}.zip dist/
          else
            echo "Dist directory not found, creating placeholder"
            mkdir -p dist
            echo "Build output will be here" > dist/README.txt
            zip -r notes-app-${{ github.ref_name }}.zip dist/
          fi
      
      # Create GitHub Release - Using GitHub CLI instead
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "## 🎉 Release ${{ github.ref_name }}
            
            ### Changes in this release:
            - Check commit history for detailed changes
            
            ### Installation:
            1. Download the zip file
            2. Extract to your web server
            3. Open index.html in your browser" \
            ./notes-app-${{ github.ref_name }}.zip